version: '3.7'

networks:
  hestia-network-dev:
    name: hestia-network-dev

volumes:
  hestia-database-volume-dev:
    name: hestia-database-volume-dev

services:
  hestia-bot-dev:
    container_name: hestia-bot-dev
    healthcheck:
      test: cat /proc/1/cmdline || exit 1
      start_period: 5s
    image: wtfloris/hestia-bot:dev
    networks: 
      - hestia-network-dev
    restart: unless-stopped
    volumes:
      - /root/hestia-dev/data:/data
    working_dir: /hestia

  hestia-scraper-dev:
    container_name: hestia-scraper-dev
    healthcheck:
      test: pgrep cron || exit 1
      start_period: 5s
    image: wtfloris/hestia-scraper:dev
    networks: 
      - hestia-network-dev
    restart: unless-stopped
    volumes:
      - /root/hestia-dev/data:/data
    working_dir: /scraper

  hestia-database-dev:
    container_name: hestia-database-dev
    environment:
      POSTGRES_PASSWORD: A3kZi9j8zT3JRsu0RDcbxjIr
    image: postgres:latest
    networks: 
      - hestia-network-dev
    ports:
      - "127.0.0.1:54321:5432"
    restart: unless-stopped 
    volumes:
      - hestia-database-volume-dev:/var/lib/postgresql/data
