version: '3.7'
services:
  hestia-bot:
    container_name: hestia-bot
    image: wtfloris/hestia-bot:latest
    restart: unless-stopped
    working_dir: /hestia
    volumes:
      - /root/hestia/data:/data
    healthcheck:
      test: cat /proc/1/cmdline || exit 1
      start_period: 5s

  hestia-scraper:
    container_name: hestia-scraper
    image: wtfloris/hestia-scraper:latest
    restart: unless-stopped
    working_dir: /scraper
    volumes:
      - /root/hestia/data:/data
    healthcheck:
      test: pgrep cron || exit 1
      start_period: 5s
